### ISSUE TITLE
Landing page is wrong, should go to a different screen

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/info_manual3#114]
Landing experience is https://library.threefold.me/info/manual/#/

but should be

https://library.threefold.me/info/manual/#/getstarted/manual__tfgrid3_getstarted

**Comment by sasha-astiadi** [comment]
https://library.threefold.me/info/manual/#/manual__manual3_home_new this should be the correct link, when https://library.threefold.me/info/manual/#/ is clicked, i will fix now

**Comment by sasha-astiadi** [comment]
unfortunately this is a technical publishtools issue, only @despiegk can fix it, i couldnt, i tried @sabrinasadik

**Comment by sasha-astiadi** [comment]
@xmonader do u know how to fix this? i cant fix this one

**Comment by sasha-astiadi** [comment]
@PeterNashaat same thing like the wiki,cpuld you pls help us out on this one

**Comment by sasha-astiadi** [comment]
a lot of files are named readme files causing problems.... so i renamed them and make sure all links are updated with thr new file names

**Comment by sasha-astiadi** [comment]
fixed https://library.threefold.me/info/manual/#/ :) yay
