### ISSUE TITLE
Manual 3.0 > Concepts > Page with just links

### ISSUE THREAD

**Issue by VicObee** [threefoldfoundation/info_manual3#118]
This needs info directly on the page. When you click on concepts you want to see the concepts directly there, not be redirected for each of the concepts.

**Comment by VicObee** [comment]
https://library.threefold.me/info/manual/#/manual__manual3_home_new

**Comment by sasha-astiadi** [comment]
edited it

https://github.com/threefoldfoundation/info_manual3/commit/012e85483b430bc7ef41ce8bc487b405497b3b10

**Comment by sasha-astiadi** [comment]
https://library.threefold.me/info/manual/#/manual__manual3_concept

now live
