### ISSUE TITLE
Make planetary network connector tool more visible

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_manual3#126]
Report from the community, that the planetary network connector app is only linked from this page on the manual:
https://library.threefold.me/info/threefold/#/manual__yggdrasil_client

Suggestion to make it more visible by adding more links, perhaps to this page:
https://library.threefold.me/info/threefold/#/technology/threefold__planetary_network

**Comment by sasha-astiadi** [comment]
will add it to the sidebar, and also 
https://library.threefold.me/info/threefold/#/technology/threefold__planetary_network

should be on manual

**Comment by sasha-astiadi** [comment]
edit the manual's planetary network tutorial https://github.com/threefoldfoundation/info_manual3/pull/175

**Comment by sasha-astiadi** [comment]
add manual link  to wiki's https://library.threefold.me/info/threefold/#/technology/threefold__planetary_network

pr: https://github.com/threefoldfoundation/info_threefold_pub/commit/472b3c29e095f0909ba7b94345e6840f35d24077

**Comment by sasha-astiadi** [comment]
done
