### ISSUE TITLE
show yggdrassil peers in a more visible place in the manual

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#130]

**Comment by despiegk** [comment]
and group them per region (if needed at public ones to them if not enough of ours)

- west europe
- us 
- canada
- ...

this will give locality, we need to create a star, so our yggdr nodes know about their peers elsewhere, need to see how yggdrasil prioritizes, need to make sure its always the close ones (order in config file?)

we also need to make sure that the zos'es use entry nodes close to them (this is ok for 3.9), we need to cut the map in pieces, western europ, eastern, middle east, africa, canada, us, ... and each of them having entry points
also some pub ones if we don't have enough ourselves

this will give us locality

**Comment by xmonader** [comment]
e3f45087dee5d090b4b4fe3232c1aa7956ebd9e3
