### ISSUE TITLE
readd the documentation on the ip range

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#131]
```
  ip_range     = lookup(grid_network.net1.nodes_ip_range, 34, "")
```

this specific usage

**Comment by mariobassem** [comment]
ip_range value in next release (v1.5.9 ) is going to be automatically computed and user won't provided it as input. This change was done here (https://github.com/threefoldtech/terraform-provider-grid/pull/361)
Also, all examples will be updated too.
