### ISSUE TITLE
add docs for the grace period

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#132]
- the new state in zos `paused`
- when it gets kicked in
- how to resume your workload
- how can you see if a contract in a graceperiod or not

**Comment by DylanVerstraete** [comment]
Some small comments to improve writing documentation:

- Grace period kick in when your wallet has no more funds
- Grace period is active during 2 weeks
- If you funded your wallet within 2 weeks, then after max 1 hour your deployments should be live again
- If you did not fund your wallet within 2 weeks, your deployments are canceled
- Can check if your contracts are in graceperiod in Graphql, polkadotJS UI (chainstate -> SmartContractModule -> Contracts(ID_OF_CONTRACT) -> check state

**Comment by xmonader** [comment]
@mohamedamer453 can't we also see the contract status in the contracts listing in the playground?

**Comment by mohamedamer453** [comment]
> @mohamedamer453 can't we also see the contract status in the contracts listing in the playground?

Yes we can i'm currently creating the docs and i've added all of the ways that the user can access the contract state from including the contracts tab in the weblets, gridproxy, graphql, and polkadot ui

**Comment by mohamedamer453** [comment]
added in https://github.com/threefoldfoundation/info_manual3/pull/133

**Comment by xmonader** [comment]
https://github.com/threefoldfoundation/info_manual3/pull/133
