### ISSUE TITLE
Missing documents on freeflow From stars to spheres

### ISSUE THREAD

**Issue by A-Harby** [threefoldfoundation/info_manual3#138]
https://library.threefold.me/info/freeflow/#/collaboration/freeflow__stars_vs_spheres

![image](https://user-images.githubusercontent.com/109473873/205618903-ac0edf71-b06a-44aa-9bb1-a1a1214a2f6e.png)
![image](https://user-images.githubusercontent.com/109473873/205618937-f7a67ea5-e0a9-40a1-bcf8-bc26989db23c.png)

**Comment by sasha-astiadi** [comment]
will remove thw section in general thank you

**Comment by sasha-astiadi** [comment]
its in freeflow wiki

**Comment by sasha-astiadi** [comment]
https://github.com/freeflowuniverse/info_freeflow_pub/commit/83bc252b55e4800173df74a6be31ee72dc9b303a
