### ISSUE TITLE
For Mastodon weblet, please add "what happens if I forgot to fund my mastodon server"

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_manual3#139]
We need to clarify in the manual for the mastodon weblet what happens when the person runs out of funds, based on conversation with Thabet. See https://library.threefold.me/info/manual/#/manual__grace_period?id=grace-period

**Comment by sasha-astiadi** [comment]
added on development_mastodonL threefold_mastodon/threefold_mastodon.md

**Comment by sasha-astiadi** [comment]
dine
