### ISSUE TITLE
Incorrect guide on how to bridge from Stellar to TFChain 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#141]
See https://library.threefold.me/info/manual/#/manual__dashboard_readme

Incorrect information.

![Screenshot 2022-12-12 at 15 57 09](https://user-images.githubusercontent.com/31733464/207079499-dc3fc29b-86ae-4799-8d5e-1669d3a21078.png)

![photo_2022-12-12 16 06 42](https://user-images.githubusercontent.com/31733464/207079917-d800796b-1df1-4ffd-ac99-e380ec43f850.jpeg)

**Comment by sasha-astiadi** [comment]
new one should be on info_grid
