### ISSUE TITLE
Cover full VMs and how to upgrade them with Terraform

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_manual3#155]
Terraform docs don't mention distinctions between micro VMs and full VMs. Namely:
* Only the flist determines which one we get
* Full VMs ignore the rootfs field and use the first mount as their rootfs
* We can upgrade a full VM by tearing it down, leaving the disk in detached state, then reattaching disk to new VM

**Comment by sasha-astiadi** [comment]
track here https://github.com/threefoldtech/info_grid/issues/114
