### ISSUE TITLE
Better landing page

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_manual3#157]
Currently, the landing page for the manual leads visitors to deploy their "first VM". Since farmers also visit the manual, this can be confusing—the farmers think they need a VM to start farming.

Instead, let's have a landing page the presents different paths someone might take, including the first VM route. These might be:

1. Get started - first VM
2. Farming
3. Learn about grid concepts
4. Learn about grid services and data sources
5. Advanced deployment techniques (Terraform)

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_manual3/commit/6a08c6f687c94ceac73e791a9248d129e9a8b444

**Comment by sasha-astiadi** [comment]
https://library.threefold.me/info/manual/#/ updated
