### ISSUE TITLE
Wiki - Stellar to TFChain transfer on the TF Connect app 

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/info_manual3#162]
The transfer of TFTs from Stellar to TFChain needs a memo on the TF Connect app for the transfer to be successful, but the wiki does not state that info https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge  
![Stellar to TFChain](https://user-images.githubusercontent.com/88147124/223676958-14dd76a1-e012-4b99-8ac4-8d63df9cc3c1.jpg)

also, the wallet address is incorrect. 

The correct wallet address should be GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC 
The memo should be twin_<twinId> (the respective person's twin id)

**Comment by sabrinasadik** [comment]
@sasha-astiadi pls change this on the wiki

**Comment by sasha-astiadi** [comment]
will do @sabrinasadik thanks!

**Comment by sasha-astiadi** [comment]
fixed https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge
