### ISSUE TITLE
Update discount level thresholds

### ISSUE THREAD

**Issue by renauter** [threefoldfoundation/info_manual3#164]
According to tchain changes to come on discount level
(see https://github.com/threefoldtech/tfchain/issues/637)
the following links should be updated:

- https://library.threefold.me/info/manual/#/threefold__pricing?id=discount-levels
- https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=discount-on-staked-tokens

with the following new thresholds values (old values reduced by half):

 | discount level | pricing discount | nr months staking |
 | -------------- | -----------------| ----------------- |
 | none           | - 0%             | 0 month           |
 | default        | - 20%            | 1.5 months        |
 | bronze         | - 30%            | 3 months          |
 | silver         | - 40%            | 6 months          |
 | gold           | - 60%            | 18 months         |

**Comment by renauter** [comment]
I guess it needs to be updated here:
https://github.com/threefoldfoundation/info_threefold_pub/blob/43ea2d5440c241319a6ea9852014f22783941651/wiki/tfgrid/pricing/staking_discount_levels0.md
correct? @sasha-astiadi

**Comment by sasha-astiadi** [comment]
@renauter hi erwan, thanks! i will update that one now!

**Comment by renauter** [comment]
Great!
In terms of timing, this update should be published when 3.10 comes live on mainnet I guess

**Comment by sasha-astiadi** [comment]
ok so not now? got it

**Comment by sasha-astiadi** [comment]
Links to update:

https://library.threefold.me/info/manual/#/threefold__pricing?id=discount-levels
https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=discount-on-staked-tokens

**Comment by sasha-astiadi** [comment]
can you please also update the calculation:

40% discount example (old one / current one on https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=discount-on-staked-tokens):
[
- I've used 10 TFT worth of Internet Capacity on tf_grid for the last hour.
- 10TFT * 24 * 30 * 12 = I would need x TFT for one year
- 10TFT * 24 * 30 * 36 = I would need x TFT for 3 year
- I have 120,000 TFT in my account on TF_Chain, this means that I will get 40% discount.
- I don't have enough tokens to get to 60% discount.](https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=discount-on-staked-tokens)

**Comment by renauter** [comment]
I also reworked the text to make the example more readable

[Example for 40% discount eligibility](https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=example-for-40-discount)

- Let say my Internet Capacity consumption on ThreeFold Grid is 10 TFT per hour worth.
- Scaled to 6 months it gives 10 TFT * 24h * 30d * 6m = 43,200 TFT which is the minimum amount to have in my account to be eligible for 40% discount
- Scaled to 18 months it gives  10 TFT * 24h * 30d * 18m = 129,600 TFT which is the minimum amount to have in my account to be eligible for 60% discount
- So if I have 60,000 TFT in my account on TFChain, this means I will get 40% discount.
- I don’t have enough tokens to get to 60% discount.
- Taking into account the 40% discount I will effectively pay this consumption 6 TFT per hour as long as the amount of TFT in my account belongs to the range specified above

**Comment by sasha-astiadi** [comment]
| type       | pricing level | nr months of TFT linked to account |
| ---------- | ------------- | ---------------------------------- |
| no staking | - 0%          | 0                                  |
| default    | - 20%         | 1.5 months                           |
| bronze     | - 30%         | 3 months                           |
| silver     | - 40%         | 6 months                          |
| gold       | - 60%         | 18 months                          |

TFChain charges the user for proof_of_utilization every hour. TFChain will calculate the discount based on amount of TFT available in the account of the user on TFChain (not on Stellar or any of the other blockchains we also support). This is an automatic form of staking, the user does not have to do anything to have this benefit. For network related services its max 40% discount.

### Example for 40% discount

- Let say my Internet Capacity consumption on ThreeFold Grid is 10 TFT per hour worth.
- Scaled to 6 months it gives 10 TFT * 24h * 30d * 6m = 43,200 TFT which is the minimum amount to have in my account to be eligible for 40% discount
- Scaled to 18 months it gives 10 TFT * 24h * 30d * 18m = 129,600 TFT which is the minimum amount to have in my account to be eligible for 60% discount
- So if I have 60,000 TFT in my account on TFChain, this means I will get 40% discount.
- I don’t have enough tokens to get to 60% discount.
- Taking into account the 40% discount I will effectively pay this consumption 6 TFT per hour as long as the amount of TFT in my account belongs to the range specified above

**Comment by sasha-astiadi** [comment]
@renauter Let me know. if all ok

**Comment by renauter** [comment]
> * my account belongs to the range specified above

would change to:

... my account belongs to the [43,200; 129,600] range (see calculation above).

**Comment by sasha-astiadi** [comment]
got it. so only release once we release v3.10 on mainnet? or testnet?

**Comment by sasha-astiadi** [comment]
@renauter

**Comment by renauter** [comment]
I guess this information needs to be online when 3.10 is on mainnet since the available online documentation should be related to the production environment which is more relevant for users/farmers.
If we put this info online sooner it could be confusing for community (people could think is already live on mainnet)

**Comment by sasha-astiadi** [comment]
ok thanks erwan, will only put this on if we're live on 3.10

**Comment by sasha-astiadi** [comment]
FILES TO CHECK @renauter @rkhamis @robvanmieghem anyone from product

1. CLOUD UNIT PRICING - LIBRARY
https://github.com/threefoldfoundation/info_threefold_pub/blob/3.10.0/wiki/tfgrid/pricing/cloudunits_pricing.md?plain=1

2. TFCHAIN PRICING -- MANUAL
https://github.com/threefoldfoundation/info_manual3/blob/3.10.0/wiki/tfchain/tfchain_pricing.md?plain=1

3. CLOUD PRICING COMPARE - LIBRARY 
https://github.com/threefoldfoundation/info_threefold_pub/blob/3.10.0/wiki/tfgrid/pricing/cloud_pricing_compare.md?plain=1

4. LEGAL - FARMER T&C
https://github.com/threefoldfoundation/info_legal/blob/development/wiki/terms_conditions_farmer_parts/part_9_capacity_utilization.md?plain=1

**Comment by robvanmieghem** [comment]
@DylanVerstraete doing a shout-out to you as you created https://github.com/threefoldtech/tfchain/issues/637

**Comment by sasha-astiadi** [comment]
will bring these 4 to the new info_grid as well. would be nice to have as we upgrade it to mainnet on both old and new manuals

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_threefold_pub/blob/3.10.0/wiki/tfgrid/pricing/cloudunits_pricing.md?plain=1
