### ISSUE TITLE
duplicate update discount level on manual

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_manual3#169]
https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge

request by @renauter https://github.com/threefoldfoundation/info_manual3/issues/164

**Comment by renauter** [comment]
> https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge

I think this link is not the good one

Links to update:
   - https://library.threefold.me/info/manual/#/threefold__pricing?id=discount-levels
   - https://library.threefold.me/info/manual/#/manual__proof_of_utilization_manual?id=discount-on-staked-tokens

**Comment by sasha-astiadi** [comment]
sorry duplicated, ill closs this one, ill movw your comment to the issue you made previously
