### ISSUE TITLE
Locked tokens overview: link broken 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#171]
https://library.threefold.me/info/threefold#/tokens/threefold__token_overview

Clicking on 'Locked tokens overview' doesnt work.

**Comment by amandacaster** [comment]
https://library.threefold.me/info/threefold#/tokens/threefold__token_overview?id=threefold-token-overview - The locked tokens overview needs to be updated/changed as it is not opening but not able to find the info on the .md file to make changes. 

![photo_2023-04-27_19-08-15](https://user-images.githubusercontent.com/88147124/234880691-0314023e-c8c2-4c82-9b8b-fad810bbc3b2.jpg)

**Comment by amandacaster** [comment]
Since all the links that need to be fixed are on https://github.com/threefoldfoundation/info_threefold_pub/issues/114 hence closing this one, and all updates will be on https://github.com/threefoldfoundation/info_threefold_pub/issues/114
