### ISSUE TITLE
Change vesting overview in wiki 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#172]
https://library.threefold.me/info/threefold#/tokens/threefold__vesting_overview
Should reflect the forum post, see https://forum.threefold.io/t/unvesting-tfts/3912/2

**Comment by sabrinasadik** [comment]
Also remove the vesting section on https://library.threefold.me/info/threefold#/tokens/threefold__tokenomics

**Comment by amandacaster** [comment]
Updates of this ticket are on https://github.com/threefoldfoundation/info_threefold_pub/issues/112 as the changes were able to be made on the info_threefold_pub repo.

**Comment by sasha-astiadi** [comment]
@amandacaster pls dont close the issue, im in the middle of reviewing.

**Comment by sasha-astiadi** [comment]
update: two tasks:

- [ ] edit https://library.threefold.me/info/threefold#/tokens/threefold__vesting_overview
to reflect the forum post, see https://forum.threefold.io/t/unvesting-tfts/3912/2 @sasha-astiadi 

- [x] remove 'vesting' section on https://library.threefold.me/info/threefold#/tokens/threefold__tokenomics @amandacaster
https://github.com/threefoldfoundation/info_threefold_pub/issues/112

**Comment by sasha-astiadi** [comment]
remove 'vesting' section on https://library.threefold.me/info/threefold#/tokens/threefold__tokenomics @amandacaster
https://github.com/threefoldfoundation/info_threefold_pub/issues/112

done by amanda, https://github.com/threefoldfoundation/info_threefold_pub/commit/5f58e79f4b7062a5e1780584b1734cee795ee5d4

**Comment by sasha-astiadi** [comment]
now i need to  edit https://library.threefold.me/info/threefold#/tokens/threefold__vesting_overview
to reflect the forum post, see https://forum.threefold.io/t/unvesting-tfts/3912/2

**Comment by sasha-astiadi** [comment]
@sabrinasadik open pr https://github.com/threefoldfoundation/info_threefold_pub/pull/117

**Comment by sasha-astiadi** [comment]
pr approved

**Comment by amandacaster** [comment]
Reopening this to adjust the layout of the unvesting under https://library.threefold.me/info/threefold#/tokens/threefold__unvesting
