### ISSUE TITLE
Change zos version in 3.9 release notes

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#173]
On the release notes in the library https://library.threefold.me/info/manual/#/manual__tfgrid_release_3_9_0

First it says 3.6.0 rc this needs to be just 3.6.0

<img width="350" alt="Screenshot 2023-04-28 at 13 45 26" src="https://user-images.githubusercontent.com/31733464/235139418-f8660665-ce18-43ef-8bf5-1c5abfb5d843.png">

Below it says 3.5.0
<img width="650" alt="Screenshot 2023-04-28 at 13 45 38" src="https://user-images.githubusercontent.com/31733464/235139444-f93f109f-336e-40b4-a314-a501074f9bfd.png">

Pls change both to 3.6.0

**Comment by amandacaster** [comment]
Changes made - https://github.com/threefoldfoundation/info_manual3/pull/174

**Comment by sasha-astiadi** [comment]
done https://library.threefold.me/info/manual/#/manual__tfgrid_release_3_9_0
