### ISSUE TITLE
migrate old manual to the new manual manual.grid.tf

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_manual3#176]
new manual repo: https://github.com/threefoldtech/info_grid

me and karoline discussed with kds , he wanna  take down the old one and just keep the new one @rkhamis @xmonader @sabrinasadik @Mik-TF and please let dev know. 

<img width="1120" alt="Screenshot 2023-05-03 at 14 25 21" src="https://user-images.githubusercontent.com/43240801/235914901-f5af9783-ad23-447a-ba8e-529c27a67519.png">

and here is my proposal on how we could move forward:
we need to slowly take down the old manual instead of taking it down at once, just in case we still need some information on the old one, that havent been transferred yet to the new manual.

**- suggesting users to go to new manual**
- [x] add the new manual link on the old manual homepage for now and suggest users to go to the new manual
- [x] replace the old manual links on TF website with the new one

**- proofread old manual and migration**
- [x] [get web team and support team to proofread old manual](https://github.com/threefoldtech/tf_support/issues/466), find duplicated articles that have been transferred to new one, as well as the articles that have not been transferred to the new one
- [x] transfer old issues from old manual repo to the new one
- [x] provide list of old articles that have not been migrated to the new one, and discuss with dev team on what's deemed necessary to include to the new manual
- [x] migrate old articles to the new one , only if necessary

ALL DUPLICATED INFOS ARE KEPT ON THIS SHEET
https://docs.google.com/spreadsheets/d/14lfBga4P_GT_vs2DLV_fgBD7AiIvLPnarlbpxONgsRk/edit?usp=sharing

**deactivate the old manual**
- [x] after migration is finished, ask ops to redir manual.threefold.io to the new manual.grid.tf
- [x] keep old manual repo as archived

**documentation**
- [x] make a tutorial on how to use mdbooks and add it to the new manual 
- [ ] publish on forum and channels how we have migrated from the old to new manual.

---

## migrate content:

new contents:

- new intro
- update how it works
- add grid concepts
- add tfchain
- add glossary / component list
- add mastodon deployer
- add nixos microvm
- add website zola tool
- add circle tool
- add IaC
- add redis
- add help us test
- add roadmap + release notes

**Comment by mik-tf** [comment]
I checked the task: make a tutorial.

Here is the tutorial: https://www2.manual.grid.tf/contribute/contribute.html#how-to-contribute-to-the-threefold-manual

If it's not clear enough or something is missing, let me know and I will adjust accordingly.

I updated the section to be clearer.

**Comment by sasha-astiadi** [comment]
there seems in general a confusion between team members that
the content of Threefold Library (anything under [library.threefold.me](https://github.com/threefoldfoundation/info_manual3/issues/library.threefold.me)) , under repo [info_threefold_pub](https://github.com/threefoldfoundation/info_threefold_pub),
still valid, active, and different to the old manual..

meanwhile the old manual is hosted on [manual.threefold.io](https://github.com/threefoldfoundation/info_manual3/issues/manual.threefold.io) under repo [info_manual3](https://github.com/threefoldfoundation/info_manual3).

anything from the library, such as this legal, doesnt need to be migrated to the new manual, link is ok,
the only things needed to be migrated are content that exist on info_manual3 repo / [manual.threefold.io](https://github.com/threefoldfoundation/info_manual3/issues/manual.threefold.io)
