### ISSUE TITLE
update the usage of env vars in terraform docs

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#18]

**Comment by ashraffouda** [comment]
updated

**Comment by mhost39** [comment]
Verified 
https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_vm
![image](https://user-images.githubusercontent.com/31102305/147761497-1ad8006e-daa2-4b93-bab8-ad4d9fe0d27e.png)
