### ISSUE TITLE
Move website tool from old library to new Manual

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_manual3#185]
Move [website tool](https://library.threefold.me/info/manual/#/manual__website) from old library to new [Manual](https://manual.grid.tf/)

**Comment by sasha-astiadi** [comment]
ading sidebar on summary.md is enough, the link is https://library.threefold.me/info/legal/#/ 

there seems in general a confusion between team members that 
the content of **Threefold Library** (anything under **[library.threefold.me](library.threefold.me)**) , under repo [info_threefold_pub](https://github.com/threefoldfoundation/info_threefold_pub), 
 still valid, active, and different to the old manual..


meanwhile the old manual is hosted on [manual.threefold.io](manual.threefold.io) under repo [info_manual3](https://github.com/threefoldfoundation/info_manual3).

anything from the library, such as this legal, doesnt need to be migrated to the new manual, link is ok,
the only things needed to be migrated are content that exist on info_manual3 repo / [manual.threefold.io](manual.threefold.io)
