### ISSUE TITLE
Move Advanced > Stellar - TF Chain Bridge from Old Library to New Manual

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_manual3#188]
Move Advanced > [Stellar - TF Chain Bridge](https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge) from Old Library to New [Manual](https://manual.grid.tf/)

**Comment by amandacaster** [comment]
Data was found under a different heading https://manual.grid.tf/getstarted/TF_Dashboard/TF_Dashboard.html#transfer-tft-from-stellar-chain-to-tfchain, but more TFChain to Stellar details needs to be added transferred

**Comment by sasha-astiadi** [comment]
@amandacaster already existed here dear :) https://manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html?highlight=tfchain%20bridge#how-to-use-the-tfchain-stellar-bridge
