### ISSUE TITLE
Move Advanced > Keygen Token Transfer from Old Library to New Manual

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_manual3#189]
Move Advanced > [Keygen Token Transfer](https://library.threefold.me/info/manual/#/manual__token_transfer_keygenerator) from Old Library to New [Manual](https://manual.grid.tf/)

**Comment by Mahmoud-Emad** [comment]
Should be moved in https://github.com/threefoldtech/info_grid/pull/77

**Comment by sasha-astiadi** [comment]
@Mahmoud-Emad i handover this one to you to add to new manual thank you. do you need to make new issue on new one?

**Comment by Mahmoud-Emad** [comment]
@sasha-astiadi
I was working on [this issue](https://github.com/threefoldtech/info_grid/issues/73) and the link that mentioned here was a part of the missing docs I added, I mentioned the PR above, you can check if the advanced tab included.

I'll remove myself from the assigners and remove it also from verification.

**Comment by sasha-astiadi** [comment]
@Mahmoud-Emad thank you i will check

**Comment by sasha-astiadi** [comment]
done on staging https://www2.manual.grid.tf/advanced/token_transfer_keygenerator.html thank y9ou @Mahmoud-Emad
