### ISSUE TITLE
Broken links in grid3 developer basic 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldfoundation/info_manual3#20]
https://library.threefold.me/info/manual/#/manual3_iac/manual__grid3_developer_basics

![image](https://user-images.githubusercontent.com/41957921/143764904-9ccbd8c3-75b5-4b9e-91f3-5c7d2cef8548.png)

![image](https://user-images.githubusercontent.com/41957921/143764992-f1f0584b-530d-4f4e-bd7e-21d0602d2ba6.png)

**Comment by mhost39** [comment]
Verified 
https://library.threefold.me/info/manual/#/manual3_iac/manual__grid3_developer_basics
