### ISSUE TITLE
Terraform: Getting started deployment example needs an update

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldfoundation/info_manual3#22]
https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_get_started?id=using-terraform

in this example, it creates a network without `add_wg_access`, but it prints wg config in the output and this config will be empty, so I think it should contain `add_wg_access = true`
```tf
...

resource "grid_network" "net1" {
    nodes = [2, 4]
    ip_range = "10.1.0.0/16"
    name = "network"
    description = "newer network"
    add_wg_access = true
}

...

```

**Comment by ashraffouda** [comment]
updated

**Comment by mhost39** [comment]
still not updated on getting start example 
https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_get_started
![image](https://user-images.githubusercontent.com/31102305/147756428-5c43e794-7716-494e-b17b-e202b2d07af2.png)

**Comment by xmonader** [comment]
add_wg_access exists on the examples, the main terraform getstarted doesn't have code example anymore after kristof's refactor
