### ISSUE TITLE
update the the supported flists to the official apps links

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#31]
see the ones mentioned here https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_supported_flists to use https://github.com/threefoldtech/grid_weblets/pull/304

**Comment by mhost39** [comment]
Verified 
https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_supported_flists
