### ISSUE TITLE
Manual seems to be outdated - no 'manage' button

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#40]
![Screenshot 2022-02-14 at 16 31 35](https://user-images.githubusercontent.com/31733464/153894151-d6095286-6880-411e-b800-6ec44a6029ae.png)
![Screenshot 2022-02-14 at 16 31 30](https://user-images.githubusercontent.com/31733464/153894158-2c20f217-eb42-42b9-ab61-c411e597c63a.png)

**Comment by gmachtel** [comment]
Updated in https://github.com/threefoldfoundation/info_manual3/tree/development/wiki/tfchain_portal , yet to be published.

**Comment by gmachtel** [comment]
Is published
