### ISSUE TITLE
more information for farmer setup

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#42]
Each large farmer needs to have their own pub network with Yggdrasil public router and webgw.

Need to check with the operations team, how we make this happen, there need to be doc for a farmer, we should have a process to check today even manual is ok.

**Comment by coesensbert** [comment]
It basically comes down to this regarding public config

Polkadot js: https://polkadot.js.org/

Add public config to nodes:
* Developer -> Extrinsics
* Choose the correct account
* tfgridmodule -> addNodePublicConfig(farmid, nodeid, publicConfig)
* farm id / node id / ipv4 / ipv6 / gw4 / gw6 -> ADD IP's IN CIDR

Adding IP's to a farm can now easily be done from the portal: https://library.threefold.me/info/threefold#/manual__tfchain_portal_ui_farming?id=add-a-public-ip-to-your-farm

**Comment by coesensbert** [comment]
Found this:
- Public config:
https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/farming/public_config.md

- Farm IP
https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/tfchain_portal/tfchain_portal_ui_farming.md

@xmonader is this enough? Should it be extended or add something?

**Comment by coesensbert** [comment]
It's now possible to add a node public config in the portal! :fireworks: 

![image](https://user-images.githubusercontent.com/88312671/155116502-d55b42ac-2d01-452c-8778-533b19c33ca4.png)

**Comment by xmonader** [comment]
a6b9277f4ed1c3f64863dd577a065421e233ae8d
