### ISSUE TITLE
 Farming documentation - precision on starting 3node

### ISSUE THREAD

**Issue by renauter** [threefoldfoundation/info_manual3#53]
Information about keeping USB Stick on 3node (Titan or Diy) when restarting is missing
Recommendation is to always keep it plugged-in

### Explanation
Keep USB stick plugged-in because it contains info for starting
At first starting it creates a minimum requirement on SSD which is used as cache
Each time the system restarts it reuse this SSD piece but USB stick is needed to download again the last image
Image is not stored on the machine and also no boot loader is installed

@maxux Please review if explanation correct

### Suggestion
To be completed [here](https://library.threefold.me/info/manual/#/manual__booting_node) in manual
with obvious/visible warning

**Comment by sasha-astiadi** [comment]
@renauter are you going to write the documentation or can you suggest who could do it?

**Comment by renauter** [comment]
Yes, I can do it and ask for appropriate review

@sasha-astiadi Edit should be done here 
https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/farming/booting_node.md
right?

**Comment by sasha-astiadi** [comment]
@renauter correct, please edit it, and let me know when done

**Comment by renauter** [comment]
> @renauter correct, please edit it, and let me know when done

I made the changes on PR and it seems that you already merged it so we are all good

**Comment by maxux** [comment]
Information is correct.

The USB contains a small boot loader which will download latest image and boot it. Node doesn't store kernel nor base image, it's always downloaded and runs in memory

:)

**Comment by sasha-astiadi** [comment]
ists published, so @maxux @renauter https://library.threefold.me/info/manual/#/manual__booting_node no changing more? ill close this issue
