### ISSUE TITLE
need to document the sizes, ... (is for terraform,...)

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_manual3#54]
there are many nr's needed e.g. size of disk, vm, ...
i cant find what these nr's are

3 possible solutions

- have query in grid proxy
- documentation
- both

**Comment by xmonader** [comment]
all of the resources and their units are documented here https://github.com/threefoldtech/terraform-provider-grid/blob/development/docs/index.md (should that be copied to the wiki it's more of a reference? and also that gets autogenerated on releasing)

**Comment by sasha-astiadi** [comment]
@xmonader @rkhamis anything to do more here ?
