### ISSUE TITLE
terraform kubernetes example

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#6]
https://library.threefold.me/info/threefold#/manual_tfgrid3/manual3_iac/grid3_terraform/threefold__terraform_k8s_example

- the example refer to old provider plugin version.
- also the output refer to network.access_wg_config but `add_wg_access` is missing from the grid_network resource inputs

**Comment by ashraffouda** [comment]
updated

**Comment by mhost39** [comment]
https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_k8s

there are output for wg_config
output "wg_config" {
    value = grid_network.net1.access_wg_config
}
and ``` add_wg_access = true ``` not added to network 

![image](https://user-images.githubusercontent.com/31102305/147873386-478640b8-9f5b-41f1-ae05-992b3ba2cfe8.png)

**Comment by sasha-astiadi** [comment]
@xmonader could we assign someone here?
