### ISSUE TITLE
update terraform kubernetes demo

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#8]
https://library.threefold.me/info/threefold#/manual_tfgrid3/manual3_iac/grid3_terraform/threefold__terraform_k8s_demo

- video show adding domain using jsng which should be achievable now using gateway and terraform?

**Comment by ashraffouda** [comment]
updated

**Comment by mhost39** [comment]
Verified 
https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_k8s_demo
