### ISSUE TITLE
Error with rendering images and links on the Digital Twin page

### ISSUE THREAD

**Issue by A-Harby** [threefoldfoundation/info_manual3#86]
There are some rendering issues with the photos and links on This [page](https://library.threefold.me/info/manual/#/twin__twin_experiences).

![image](https://user-images.githubusercontent.com/109473873/182890948-e2fc839c-261f-4a27-8a58-90226b3d6cd3.png)

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_digitalself/blob/development/wiki/use_cases/twin_experiences.md

deleted the links and img that dont work

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_digitalself/commit/4dd437f22ebc34b975043d551552edee164e48ec
