### ISSUE TITLE
Diffrent prerequisites version between grid ts client manual and repository 

### ISSUE THREAD

**Issue by A-Harby** [threefoldfoundation/info_manual3#87]
The prerequisites for node and npm required updating to the proper version.

[Manual](https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_javascript_installation)
![image](https://user-images.githubusercontent.com/109473873/183107032-09869f48-8e56-477e-b8ac-ccd06a336a22.png)

[README](https://github.com/threefoldtech/grid3_client_ts#readm)
![image](https://user-images.githubusercontent.com/109473873/183106583-36c8a890-afd5-40d3-b65b-c417a83d2526.png)

**Comment by sasha-astiadi** [comment]
which prequisite is the right one? rthe readme? ill update wiki @rkhamis

**Comment by sasha-astiadi** [comment]
archived
