### ISSUE TITLE
Document Subsquid Weblet Solution

### ISSUE THREAD

**Issue by maayarosama** [threefoldfoundation/info_manual3#89]
### Related Information
Here's some related Information that might help:
https://subsquid.medium.com/indexing-for-next-gen-dapps-unleashing-the-firesquid-56312ec4e952

**Comment by mohamedamer453** [comment]
There is a public IPv6 option mentioned, while it's not present in the latest version of the weblets. and there is a small typo in the line above it.

![image](https://user-images.githubusercontent.com/101194226/189671119-ac7de3b0-90ba-47b2-95eb-fa64c792b180.png)

**Comment by despiegk** [comment]
https://library.threefold.me/info/manual/#/manual__weblets_subsquid
