### ISSUE TITLE
threefold documentation fixes needed

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldfoundation/info_manual3#91]
- [x] - In getting started some titles of pages Appear as URLs 

![image](https://user-images.githubusercontent.com/54359761/186112548-13143a44-28d7-4952-b285-3b0161e6458a.png)

- [x] 
In activate twin needs to mention steps and website link to get the ip 

![image](https://user-images.githubusercontent.com/54359761/186113465-d0fe662e-6170-4432-ab3b-f992968a4d11.png)

- [ ] for generating the ssh key no clear steps or links are mentioned 

- [ ] There’s a wablet called node pilot in the document but doesn't exist on the website

- [x] In FAQ a lot of questions redirect to the not found page.

**Comment by sasha-astiadi** [comment]
@rkhamis please assign someone for this

**Comment by sasha-astiadi** [comment]
issue on the FAQ https://github.com/threefoldfoundation/info_manual3/issues/117

**Comment by sasha-astiadi** [comment]
all fixed manual.threefold,io, need to check on new manual
