### ISSUE TITLE
TFChain home docs

### ISSUE THREAD

**Issue by A-Harby** [threefoldfoundation/info_manual3#97]
All the links in the [TFChain home docs](https://github.com/threefoldfoundation/info_manual3/blob/28e9cdcfc417119303268b03f9e606e77a040838/wiki/tfchain/tfchain_home.md) navigate to 404 page.

**Comment by sasha-astiadi** [comment]
https://library.threefold.me/info/threefold#/getstarted/manual__tfchain_home @A-Harby on github its not openable, because we're using publishtool, but on production everything seems fine on the page
