### ISSUE TITLE
Cloud unit pricing, Need to adjust the quantity unit.

### ISSUE THREAD

**Issue by A-Harby** [threefoldfoundation/info_manual3#98]
in [Cloud unit pricing](https://library.threefold.me/info/threefold/#/tfgrid/pricing/threefold__pricing?id=cloud-pricing-it-capacity), `Network Unit (NU)` units need correction.
![image](https://user-images.githubusercontent.com/109473873/187509845-579876f0-3037-4dd5-900d-d2188d28dd99.png)

**Comment by sasha-astiadi** [comment]
@A-Harby can u tell me the exact number to correct from what to what

**Comment by A-Harby** [comment]
Seems to be miscalculation from my side, sorry for that.
